/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  114: {
    DegenDuel: {
      address: "0x835574875C1CB9003c1638E799f3d7c504808960",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "randomNumber",
              type: "uint256",
            },
          ],
          name: "BonusTriggered",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
          ],
          name: "DuelCancelled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "enum DegenDuel.DuelType",
              name: "duelType",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "stakeAmount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes21",
              name: "feedId",
              type: "bytes21",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "threshold",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "prediction",
              type: "bool",
            },
          ],
          name: "DuelCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
          ],
          name: "DuelExpired",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "joiner",
              type: "address",
            },
          ],
          name: "DuelJoined",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "winner",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "payout",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "settledValue",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "bonusApplied",
              type: "bool",
            },
          ],
          name: "DuelSettled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes21",
              name: "feedId",
              type: "bytes21",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "int8",
              name: "decimals",
              type: "int8",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "timestamp",
              type: "uint64",
            },
          ],
          name: "PriceRead",
          type: "event",
        },
        {
          inputs: [],
          name: "BONUS_CHANCE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_DURATION",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MIN_STAKE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "PROTOCOL_FEE_BPS",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "activeDuelIds",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
          ],
          name: "cancelDuel",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "dataThreshold",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "prediction",
              type: "bool",
            },
          ],
          name: "createDataDuel",
          outputs: [
            {
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes21",
              name: "feedId",
              type: "bytes21",
            },
            {
              internalType: "uint256",
              name: "priceThreshold",
              type: "uint256",
            },
            {
              internalType: "int8",
              name: "priceDecimals",
              type: "int8",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "prediction",
              type: "bool",
            },
          ],
          name: "createPriceDuel",
          outputs: [
            {
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "duels",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              internalType: "enum DegenDuel.DuelType",
              name: "duelType",
              type: "uint8",
            },
            {
              internalType: "enum DegenDuel.DuelStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "playerA",
              type: "address",
            },
            {
              internalType: "address",
              name: "playerB",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "stakeAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "deadline",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "playerAPrediction",
              type: "bool",
            },
            {
              internalType: "address",
              name: "winner",
              type: "address",
            },
            {
              internalType: "bytes21",
              name: "feedId",
              type: "bytes21",
            },
            {
              internalType: "uint256",
              name: "priceThreshold",
              type: "uint256",
            },
            {
              internalType: "int8",
              name: "priceDecimals",
              type: "int8",
            },
            {
              internalType: "uint256",
              name: "dataThreshold",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "settledValue",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "payout",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "bonusApplied",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
          ],
          name: "expireDuel",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "getActiveDuels",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "enum DegenDuel.DuelType",
                  name: "duelType",
                  type: "uint8",
                },
                {
                  internalType: "enum DegenDuel.DuelStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "address",
                  name: "playerA",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "playerB",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "stakeAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "deadline",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "playerAPrediction",
                  type: "bool",
                },
                {
                  internalType: "address",
                  name: "winner",
                  type: "address",
                },
                {
                  internalType: "bytes21",
                  name: "feedId",
                  type: "bytes21",
                },
                {
                  internalType: "uint256",
                  name: "priceThreshold",
                  type: "uint256",
                },
                {
                  internalType: "int8",
                  name: "priceDecimals",
                  type: "int8",
                },
                {
                  internalType: "uint256",
                  name: "dataThreshold",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "settledValue",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "payout",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "bonusApplied",
                  type: "bool",
                },
              ],
              internalType: "struct DegenDuel.Duel[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes21",
              name: "feedId",
              type: "bytes21",
            },
          ],
          name: "getCurrentPrice",
          outputs: [
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              internalType: "int8",
              name: "decimals",
              type: "int8",
            },
            {
              internalType: "uint64",
              name: "timestamp",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
          ],
          name: "getDuel",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "enum DegenDuel.DuelType",
                  name: "duelType",
                  type: "uint8",
                },
                {
                  internalType: "enum DegenDuel.DuelStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "address",
                  name: "playerA",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "playerB",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "stakeAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "deadline",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "playerAPrediction",
                  type: "bool",
                },
                {
                  internalType: "address",
                  name: "winner",
                  type: "address",
                },
                {
                  internalType: "bytes21",
                  name: "feedId",
                  type: "bytes21",
                },
                {
                  internalType: "uint256",
                  name: "priceThreshold",
                  type: "uint256",
                },
                {
                  internalType: "int8",
                  name: "priceDecimals",
                  type: "int8",
                },
                {
                  internalType: "uint256",
                  name: "dataThreshold",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "settledValue",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "payout",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "bonusApplied",
                  type: "bool",
                },
              ],
              internalType: "struct DegenDuel.Duel",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getOpenDuels",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "enum DegenDuel.DuelType",
                  name: "duelType",
                  type: "uint8",
                },
                {
                  internalType: "enum DegenDuel.DuelStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "address",
                  name: "playerA",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "playerB",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "stakeAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "deadline",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "playerAPrediction",
                  type: "bool",
                },
                {
                  internalType: "address",
                  name: "winner",
                  type: "address",
                },
                {
                  internalType: "bytes21",
                  name: "feedId",
                  type: "bytes21",
                },
                {
                  internalType: "uint256",
                  name: "priceThreshold",
                  type: "uint256",
                },
                {
                  internalType: "int8",
                  name: "priceDecimals",
                  type: "int8",
                },
                {
                  internalType: "uint256",
                  name: "dataThreshold",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "settledValue",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "payout",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "bonusApplied",
                  type: "bool",
                },
              ],
              internalType: "struct DegenDuel.Duel[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "player",
              type: "address",
            },
          ],
          name: "getPlayerDuels",
          outputs: [
            {
              components: [
                {
                  internalType: "uint256",
                  name: "id",
                  type: "uint256",
                },
                {
                  internalType: "enum DegenDuel.DuelType",
                  name: "duelType",
                  type: "uint8",
                },
                {
                  internalType: "enum DegenDuel.DuelStatus",
                  name: "status",
                  type: "uint8",
                },
                {
                  internalType: "address",
                  name: "playerA",
                  type: "address",
                },
                {
                  internalType: "address",
                  name: "playerB",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "stakeAmount",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "deadline",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "playerAPrediction",
                  type: "bool",
                },
                {
                  internalType: "address",
                  name: "winner",
                  type: "address",
                },
                {
                  internalType: "bytes21",
                  name: "feedId",
                  type: "bytes21",
                },
                {
                  internalType: "uint256",
                  name: "priceThreshold",
                  type: "uint256",
                },
                {
                  internalType: "int8",
                  name: "priceDecimals",
                  type: "int8",
                },
                {
                  internalType: "uint256",
                  name: "dataThreshold",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "settledValue",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "payout",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "bonusApplied",
                  type: "bool",
                },
              ],
              internalType: "struct DegenDuel.Duel[]",
              name: "",
              type: "tuple[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "player",
              type: "address",
            },
          ],
          name: "getPlayerStats",
          outputs: [
            {
              internalType: "uint256",
              name: "wins",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "earnings",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes21[]",
              name: "feedIds",
              type: "bytes21[]",
            },
          ],
          name: "getPrices",
          outputs: [
            {
              internalType: "uint256[]",
              name: "values",
              type: "uint256[]",
            },
            {
              internalType: "int8[]",
              name: "decimals",
              type: "int8[]",
            },
            {
              internalType: "uint64",
              name: "timestamp",
              type: "uint64",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getProtocolStats",
          outputs: [
            {
              internalType: "uint256",
              name: "created",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "settled",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "volume",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "fees",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getRandomNumber",
          outputs: [
            {
              internalType: "uint256",
              name: "randomNumber",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isSecure",
              type: "bool",
            },
            {
              internalType: "uint256",
              name: "randomTimestamp",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
          ],
          name: "joinDuel",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "nextDuelId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "openDuelIds",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "playerDuels",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "playerEarnings",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "playerWins",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "protocolFeePool",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
            {
              components: [
                {
                  internalType: "bytes32[]",
                  name: "merkleProof",
                  type: "bytes32[]",
                },
                {
                  components: [
                    {
                      internalType: "bytes32",
                      name: "attestationType",
                      type: "bytes32",
                    },
                    {
                      internalType: "bytes32",
                      name: "sourceId",
                      type: "bytes32",
                    },
                    {
                      internalType: "uint64",
                      name: "votingRound",
                      type: "uint64",
                    },
                    {
                      internalType: "uint64",
                      name: "lowestUsedTimestamp",
                      type: "uint64",
                    },
                    {
                      components: [
                        {
                          internalType: "string",
                          name: "url",
                          type: "string",
                        },
                        {
                          internalType: "string",
                          name: "httpMethod",
                          type: "string",
                        },
                        {
                          internalType: "string",
                          name: "headers",
                          type: "string",
                        },
                        {
                          internalType: "string",
                          name: "queryParams",
                          type: "string",
                        },
                        {
                          internalType: "string",
                          name: "body",
                          type: "string",
                        },
                        {
                          internalType: "string",
                          name: "postProcessJq",
                          type: "string",
                        },
                        {
                          internalType: "string",
                          name: "abiSignature",
                          type: "string",
                        },
                      ],
                      internalType: "struct IWeb2Json.RequestBody",
                      name: "requestBody",
                      type: "tuple",
                    },
                    {
                      components: [
                        {
                          internalType: "bytes",
                          name: "abiEncodedData",
                          type: "bytes",
                        },
                      ],
                      internalType: "struct IWeb2Json.ResponseBody",
                      name: "responseBody",
                      type: "tuple",
                    },
                  ],
                  internalType: "struct IWeb2Json.Response",
                  name: "data",
                  type: "tuple",
                },
              ],
              internalType: "struct IWeb2Json.Proof",
              name: "proof",
              type: "tuple",
            },
          ],
          name: "settleDataDuel",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "duelId",
              type: "uint256",
            },
          ],
          name: "settlePriceDuel",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalDuelsCreated",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalDuelsSettled",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalVolume",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdrawFees",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 26987490,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
